module.exports = {
    queries: [
        {
            name: 'errors per base station',
            query: `SELECT h.reason_code AS reason_code,h.description_eng AS description_eng,cnt,h.bs_id AS bs_id,h.region AS region,h.city AS city,h.standard AS standard,i.cnt_all FROM (SELECT f.reason_code AS reason_code,f.description_eng AS description_eng,sum(f.cnt) AS cnt,g.bs_id AS bs_id,g.region AS region,g.city AS city,g.standard AS standard FROM (SELECT e.reason_code AS reason_code,e.cell_id_main AS cell_id_main,e.cnt AS cnt,e.description_eng AS description_eng,e.lac_with0,e.cell_id_with0,CASE WHEN e.lac_with0 LIKE ('0%') THEN substr(lac_with0, 2) ELSE lac_with0 END AS lac,CASE WHEN e.cell_id_with0 LIKE ('0%') THEN substr(cell_id_with0, 2) ELSE cell_id_with0 END AS cell_id FROM (SELECT d.reason_code AS reason_code,d.cell_id_main AS cell_id_main,d.cnt AS cnt,d.description_eng AS description_eng,CASE WHEN cell_id_main IS NULL THEN '-99' ELSE CASE WHEN length(cell_id_main) = 15 OR length(cell_id_main) = 10 THEN substr(cell_id_main, 6, 5)ELSE substr(cell_id_main, 7, 5) END END AS lac_with0,substr(cell_id_main, 11) AS cell_id_with0 FROM (SELECT b.reason_code AS reason_code,b.cell_id_main AS cell_id_main,b.cnt AS cnt, c.description_eng AS description_eng FROM (SELECT a.reason_code AS reason_code, a.cell_id AS cell_id_main, count(*) AS cnt FROM comverse.cha a WHERE a.activity_type NOT IN ('USSD_INFO_CALL')AND @PDATE AND a.reason_code NOT IN (16)AND @REASON_CODES GROUP BY a.reason_code, a.cell_id) b LEFT JOIN biis_dimensions.DIM_PREPAID_DISCONNECT_REASON c ON b.reason_code = c.disconnect_reason_code) d) e) f JOIN biis_dimensions.stg_ref_location_area g ON f.lac = g.lac AND f.cell_id = g.cell_id GROUP BY reason_code, f.description_eng, g.bs_id, g.region, g.city, g.standard) h LEFT JOIN(SELECT sum(g.cnt) AS cnt_all,f.bs_id AS bs_id,f.region AS region,f.city AS city, f.standard AS standard FROM (SELECT e.cell_id_main AS cell_id_main,e.cnt AS cnt,e.lac_with0,e.cell_id_with0,CASE WHEN e.lac_with0 LIKE ('0%') THEN substr(lac_with0, 2) ELSE lac_with0 END AS lac,CASE WHEN e.cell_id_with0 LIKE ('0%') THEN substr(cell_id_with0, 2) ELSE cell_id_with0 END AS cell_id FROM (SELECT d.cell_id_main AS cell_id_main,d.cnt AS cnt,CASE WHEN cell_id_main IS NULL THEN '-99' ELSE CASE WHEN length(cell_id_main) = 15 OR length(cell_id_main) = 10 THEN substr(cell_id_main, 6, 5)ELSE substr(cell_id_main, 7, 5) END END AS lac_with0,substr(cell_id_main, 11) AS cell_id_with0 FROM (SELECT a.cell_id AS cell_id_main, count(*) AS cnt FROM comverse.cha a WHERE a.activity_type NOT IN ('USSD_INFO_CALL')AND @PDATE GROUP BY a.cell_id) d) e) g LEFT JOIN biis_dimensions.stg_ref_location_area f ON f.lac = g.lac AND f.cell_id = g.cell_id GROUP BY f.bs_id, f.region, f.city, f.standard) i on h.bs_id = i.bs_id and h.region = i.region and h.city = i.city and h.standard = i.standard`,
        },
        {
            name: 'distinct errors per sub',
            query: `select f.reason_code as reason_code,f.subscriber_id as subscriber_id,f.description_eng as description_eng,sum(f.cnt) as cnt,g.bs_id as bs_id,g.region as region,g.city as city,g.standard as standard,g.latitude as latitude,g.longitude as longitude,f.lac as lac,f.cell_id as cell_id from (select e.reason_code as reason_code,e.subscriber_id as subscriber_id,e.cell_id_main as cell_id_main,e.cnt as cnt,e.description_eng as description_eng,e.lac_with0,e.cell_id_with0,case when e.lac_with0 like ('0%') then substr(lac_with0, 2) else lac_with0 end as lac,case when e.cell_id_with0 like ('0%') then substr(cell_id_with0, 2) else cell_id_with0 end as cell_id from (select d.reason_code as reason_code,d.subscriber_id as subscriber_id,d.cell_id_main as cell_id_main,d.cnt as cnt,d.description_eng as description_eng,case when cell_id_main is null then '-99' else case when length(cell_id_main) = 15 or length(cell_id_main) = 10 then substr(cell_id_main, 6, 5)else substr(cell_id_main, 7, 5) end end as lac_with0,substr(cell_id_main, 11) as cell_id_with0 from (select b.reason_code as reason_code,b.cell_id_main as cell_id_main,b.subscriber_id as subscriber_id,b.cnt as cnt,c.description_eng as description_eng from (select a.reason_code as reason_code,a.cell_id as cell_id_main,a.subscriber_id as subscriber_id, count(*) as cnt from comverse.cha a where a.reason_code not in (16)AND a.reason_code in (27, 28, 32, 33)AND a.pdate in ('20190724')group by a.reason_code, a.cell_id, a.subscriber_id) b left join biis_dimensions.DIM_PREPAID_DISCONNECT_REASON c on b.reason_code = c.disconnect_reason_code) d) e) f join biis_dimensions.stg_ref_location_area g on f.lac = g.lac and f.cell_id = g.cell_id group by f.subscriber_id, f.reason_code, f.description_eng, g.bs_id, g.region, g.city, g.standard, f.lac, f.cell_id, g.latitude, g.longitude`,
        },
        {
            name: 'overall errors per sub',
            query: `select f.subscriber_id as subscriber_id, g.region as region, g.standard as standard, sum(f.cnt) as cnt from (select e.reason_code as reason_code,e.subscriber_id as subscriber_id,e.cell_id_main as cell_id_main,e.cnt as cnt,e.description_eng as description_eng,e.lac_with0,e.cell_id_with0,case when e.lac_with0 like ('0%') then substr(lac_with0, 2) else lac_with0 end as lac,case when e.cell_id_with0 like ('0%') then substr(cell_id_with0, 2) else cell_id_with0 end as cell_id from (select d.reason_code as reason_code,d.subscriber_id as subscriber_id,d.cell_id_main as cell_id_main,d.cnt as cnt,d.description_eng as description_eng,case when cell_id_main is null then '-99' else case when length(cell_id_main) = 15 or length(cell_id_main) = 10 then substr(cell_id_main, 6, 5)else substr(cell_id_main, 7, 5) end end as lac_with0,substr(cell_id_main, 11) as cell_id_with0 from (select b.reason_code as reason_code,b.cell_id_main as cell_id_main,b.subscriber_id as subscriber_id,b.cnt as cnt,c.description_eng as description_eng from (select a.reason_code as reason_code,a.cell_id as cell_id_main,a.subscriber_id as subscriber_id, count(*) as cnt from comverse.cha a where a.reason_code not in (16)AND @REASON_CODES AND @PDATE group by a.reason_code, a.cell_id, a.subscriber_id) b left join biis_dimensions.DIM_PREPAID_DISCONNECT_REASON c on b.reason_code = c.disconnect_reason_code) d) e) f join biis_dimensions.stg_ref_location_area g on f.lac = g.lac and f.cell_id = g.cell_id group by f.subscriber_id, g.region, g.standard`,
        }
    ]
}